trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Running Backend Pipeline"
    python3 app.py
  displayName: 'Run Python Hello World'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-s3-connection'
    regionName: 'us-east-1'
    command: 's3'
    arguments: 'cp "$(Build.ArtifactStagingDirectory)/app.py" s3://hello-world-devops-pc/backend/app.py --acl public-read'
  displayName: 'Upload app.py to S3'
