# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Running Backend Pipeline"
    python3 app.py
  displayName: 'Run Python Hello World'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'backend-artifacts'
